build_script:
  - cd bash-cli && gradlew.bat assemble

test_script:
  - cd bash-cli && gradlew.bat check

cache:
  - C:\Users\appveyor\.gradle

environment:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
